export const GET_PRODUCTS = 'GET_PRODUCT'
export const GET_CATEGORY = 'GET_CATEGORY'
export const SHOP_CART = 'SHOP_CART'
export const DELETE_SHOP_CART = 'DELETE_SHOP_CART'
export const STOCK='STOCK'
export const POST_ORDER='POST_ORDER'
export const PUT_ORDER='PUT_ORDER'
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_LINE = 'GET_ORDERS_LINE';
export const EDIT_ORDER_STATE = 'EDIT_ORDER_STATE';
export const FIND_ORDER_BY_PK = 'FIND_ORDER_BY_PK';
export const FIND_REVIEWS = 'FIND_REVIEWS';
export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID';
export const BUSCAR_PRODUCTO= 'BUSCAR_PRODUCTO';
export const SET_CURRENT_USER= 'SET_CURRENT_USER';
export const TRAER_REVIEWS= 'TRAER_REVIEWS';
export const PROMEDIO_ESTRELLAS= 'PROMEDIO_ESTRELLAS';
export const GET_USERS ='GET_USERS';
export const EDIT_USER_STATE ='EDIT_USER_STATE';
export const EDIT_USER ='EDIT_USER';
export const DELETE_USER ='DELETE_USER';




