export const GET_PRODUCTS = 'GET_PRODUCT'
export const GET_CATEGORY = 'GET_CATEGORY'
export const SHOP_CART = 'SHOP_CART'
export const DELETE_SHOP_CART = 'DELETE_SHOP_CART'
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_LINE = 'GET_ORDERS_LINE';
export const EDIT_ORDER_STATE = 'EDIT_ORDER_STATE';
export const FIND_ORDER_BY_PK = 'FIND_ORDER_BY_PK';
export const FIND_CURRENT_ITEM = 'FIND_CURRENT_ITEM';
export const FIND_RESULTS= 'FIND_RESULTS';
export const FIND_SUGGESTIONS= 'FIND_SUGGESTIONS';
export const BUSCAR_PRODUCTO= 'BUSCAR_PRODUCTO';


